export const HERO_PIECES = [
  { id: 'support', image: '/images/hero-soporte.jpg', material: 'PETG', target: [390, 210] },
  { id: 'gear', image: '/images/producto-engranaje.jpg', material: 'PETG', target: [330, 170] },
  { id: 'dragon', image: '/images/producto-dragon.jpg', material: 'PLA', target: [270, 180] },
  { id: 'drone', image: '/images/producto-drone.jpg', material: 'ASA', target: [450, 210] },
];

const temporaryProductImage = '/images/producto-temporal.png';

export const FEATURED_PRODUCTS = [
  { id: 'p1', material: 'PETG', status: 'ACTIVE', images: [temporaryProductImage] },
  { id: 'p2', material: 'PETG', status: 'ACTIVE', images: [temporaryProductImage] },
  { id: 'p3', material: 'PLA', status: 'ACTIVE', images: [temporaryProductImage] },
  { id: 'p4', material: 'ASA', status: 'ACTIVE', images: [temporaryProductImage] },
  { id: 'p5', material: 'ABS', status: 'ACTIVE', images: [temporaryProductImage] },
  { id: 'p6', material: 'TPU', status: 'ACTIVE', images: [temporaryProductImage] },
];

const content = {
  es: {
    heroKicker: 'Manufactura aditiva / San José, CR',
    heroTitle: 'Lo que imaginas.',
    heroAccent: 'Hecho preciso.',
    heroLead: 'Piezas funcionales, prototipos y objetos de alto detalle fabricados con criterio técnico, materiales correctos y una revisión humana en cada etapa.',
    explore: 'Explorar piezas',
    hasFile: 'Tengo un archivo',
    capabilities: 'Capacidades principales',
    orderValue: 'Bajo pedido',
    orderDetail: 'Cada pieza se fabrica después de confirmar la compra.',
    materialList: 'ASA · PLA · PETG · ABS · TPU',
    workbench: 'BANCO DE TRABAJO',
    activeReview: 'REVISIÓN ACTIVA',
    filamentLabel: 'FILAMENTO',
    previousPiece: 'Pieza anterior',
    nextPiece: 'Pieza siguiente',
    featuredPieces: 'Piezas destacadas',
    catalogKicker: 'Selección en tendencia',
    catalogTitleA: 'Lo que está',
    catalogTitleB: 'en tendencia.',
    catalogIntro: 'Cada modelo del catálogo se fabrica por encargo. Si tienes una pieza propia, revisamos tu archivo y luego preparamos una cotización.',
    methodKicker: 'El método',
    methodTitleA: 'No imprimimos',
    methodTitleB: 'por imprimir.',
    methodTitleC: 'Resolvemos.',
    methodIntro: 'Una pieza empieza mucho antes de tocar la cama de impresión: revisamos geometría, esfuerzo, material y acabado para que el resultado tenga sentido fuera de la pantalla.',
    methods: [
      ['Entender el archivo', 'Revisión de malla, escala, orientación y puntos críticos.'],
      ['Elegir el material', 'Definimos el polímero según esfuerzo, temperatura y acabado.'],
      ['Fabricar con control', 'Impresión aditiva con supervisión y revisión dimensional.'],
      ['Entregar una pieza lista', 'Retiro de soportes, revisión y preparación para despacho.'],
    ],
    precisionKicker: 'Señales de precisión',
    precisionTitleA: 'La técnica también',
    precisionTitleB: 'se puede sentir.',
    precisionIntro: 'Un sistema visual sobrio para que los datos ayuden a leer el trabajo, sin convertir la página en un panel de control.',
    specs: [
      ['Viabilidad antes de imprimir', 'Revisamos geometría, escala y orientación del archivo antes de cotizar.'],
      ['Material para cada uso', 'Trabajamos con FDM y cinco filamentos: ASA, PLA, PETG, ABS y TPU.'],
      ['Costo tras revisar', 'La cotización se define según el archivo y el alcance acordado.'],
    ],
    projectKicker: 'Tu proyecto',
    projectTitleA: '¿Tenés un archivo',
    projectTitleB: 'que quiere existir?',
    projectIntro: 'Envíanos STL u OBJ para una revisión técnica. Primero entendemos el proyecto; después construimos una cotización detallada.',
    startRequest: 'Cotizar archivo',
    viewProduct: 'Ver ficha',
    imageUnavailable: 'Imagen no disponible',
    heroPieces: {
      support: { alt: 'Soporte modular de carga en PETG', process: '/ ESTRUCTURA ALIGERADA', title: 'Soporte Modular de Carga', description: 'Estructura aligerada para montajes de carga', label: 'Pieza 1, soporte modular' },
      gear: { alt: 'Engranaje helicoidal de precisión en PETG', process: '/ MECÁNICA FDM', title: 'Engranaje Helicoidal 60T', description: 'Engranaje helicoidal de 60 dientes para transmisión mecánica', label: 'Pieza 2, engranaje helicoidal' },
      dragon: { alt: 'Dragón geométrico articulado en PLA', process: '/ MODELO ARTICULADO', title: 'Dragón de Colección', description: 'Escultura facetada con articulaciones continuas', label: 'Pieza 3, dragón geométrico' },
      drone: { alt: 'Brazo de chasis de drone en ASA', process: '/ CHASIS DE DRONE', title: 'Brazo de Chasis Drone', description: 'Estructura tubular con montaje para motor brushless', label: 'Pieza 4, brazo de drone' },
    },
    products: {
      p1: { name: 'Soporte Modular de Carga', description: 'Estructura aligerada para montajes mecánicos.', categoryName: 'Piezas funcionales', imageAlt: 'Imagen temporal para soporte modular PETG' },
      p2: { name: 'Engranaje de Precisión 60T', description: 'Dientes helicoidales para transmisión de bajo ruido y uso continuo.', categoryName: 'Mecánica / Robótica', imageAlt: 'Imagen temporal para engranaje PETG' },
      p3: { name: 'Dragón de Colección Geométrico', description: 'Escultura low-poly articulada, impresa como una pieza móvil.', categoryName: 'Colección / Arte', imageAlt: 'Imagen temporal para pieza de colección PLA' },
      p4: { name: 'Brazo de Chasis de Drone', description: 'Estructura tubular con montura para motor brushless.', categoryName: 'Drones', imageAlt: 'Imagen temporal para brazo de chasis ASA' },
      p5: { name: 'Maqueta Arquitectónica', description: 'Modelo con vanos definidos, terrazas y textura de fachada.', categoryName: 'Arquitectura', imageAlt: 'Imagen temporal para maqueta ABS' },
      p6: { name: 'Pieza Flexible de Precisión', description: 'Referencia temporal mientras se incorporan fotografías de producto.', categoryName: 'Piezas funcionales', imageAlt: 'Imagen temporal para producto TPU' },
    },
  },
  en: {
    heroKicker: 'Additive manufacturing / San José, CR',
    heroTitle: 'What you imagine.',
    heroAccent: 'Made precise.',
    heroLead: 'Functional parts, prototypes and high-detail objects made with technical judgment, the right materials and human review at every stage.',
    explore: 'Explore parts',
    hasFile: 'I have a file',
    capabilities: 'Main capabilities',
    orderValue: 'Made to order',
    orderDetail: 'Each piece is made after the order is confirmed.',
    materialList: 'ASA · PLA · PETG · ABS · TPU',
    workbench: 'WORKBENCH',
    activeReview: 'ACTIVE REVIEW',
    filamentLabel: 'FILAMENT',
    previousPiece: 'Previous piece',
    nextPiece: 'Next piece',
    featuredPieces: 'Featured pieces',
    catalogKicker: 'Trending picks',
    catalogTitleA: "What's",
    catalogTitleB: 'in the spotlight.',
    catalogIntro: 'Each catalog model is made to order. For a custom part, we review your file and then prepare a quote.',
    methodKicker: 'The method',
    methodTitleA: 'We do not print',
    methodTitleB: 'just to print.',
    methodTitleC: 'We solve.',
    methodIntro: 'A part begins long before it reaches the print bed: we review geometry, load, material and finish so the result makes sense beyond the screen.',
    methods: [
      ['Understand the file', 'Review mesh, scale, orientation and critical points.'],
      ['Choose the material', 'We select the polymer according to load, temperature and finish.'],
      ['Manufacture with control', 'Additive manufacturing with supervision and dimensional review.'],
      ['Deliver a ready part', 'Remove supports, inspect and prepare it for dispatch.'],
    ],
    precisionKicker: 'Precision signals',
    precisionTitleA: 'Technique should also',
    precisionTitleB: 'be something you feel.',
    precisionIntro: 'A restrained visual system where data helps explain the work without turning the page into a control panel.',
    specs: [
      ['Feasibility before printing', 'We review the file geometry, scale and orientation before quoting.'],
      ['Material for the intended use', 'We work with FDM and five filaments: ASA, PLA, PETG, ABS and TPU.'],
      ['Cost after review', 'The quote is based on the file and the agreed scope.'],
    ],
    projectKicker: 'Your project',
    projectTitleA: 'Have a file',
    projectTitleB: 'that should exist?',
    projectIntro: 'Send us an STL or OBJ for a technical review. We understand the project first, then build a detailed quote.',
    startRequest: 'Quote a file',
    viewProduct: 'View details',
    imageUnavailable: 'Image unavailable',
    heroPieces: {
      support: { alt: 'PETG modular load support', process: '/ LIGHTWEIGHT STRUCTURE', title: 'Modular Load Support', description: 'Lightweight structure for load-bearing assemblies', label: 'Piece 1, modular support' },
      gear: { alt: 'Precision PETG helical gear', process: '/ FDM MECHANICS', title: '60T Helical Gear', description: '60-tooth helical gear for mechanical transmission', label: 'Piece 2, helical gear' },
      dragon: { alt: 'Articulated geometric dragon in PLA', process: '/ ARTICULATED MODEL', title: 'Collectible Dragon', description: 'Faceted sculpture with continuous joints', label: 'Piece 3, geometric dragon' },
      drone: { alt: 'ASA drone chassis arm', process: '/ DRONE CHASSIS', title: 'Drone Chassis Arm', description: 'Tubular structure with brushless motor mount', label: 'Piece 4, drone arm' },
    },
    products: {
      p1: { name: 'Modular Load Support', description: 'Lightweight structure for mechanical assemblies.', categoryName: 'Functional parts', imageAlt: 'Temporary image for PETG modular support' },
      p2: { name: 'Precision Gear 60T', description: 'Helical teeth for low-noise transmission and continuous use.', categoryName: 'Mechanics / Robotics', imageAlt: 'Temporary image for PETG gear' },
      p3: { name: 'Geometric Collectible Dragon', description: 'Articulated low-poly sculpture printed as one moving piece.', categoryName: 'Collection / Art', imageAlt: 'Temporary image for PLA collectible piece' },
      p4: { name: 'Drone Chassis Arm', description: 'Tubular structure with a brushless motor mount.', categoryName: 'Drones', imageAlt: 'Temporary image for ASA drone arm' },
      p5: { name: 'Architectural Model', description: 'Model with defined openings, terraces and facade texture.', categoryName: 'Architecture', imageAlt: 'Temporary image for ABS model' },
      p6: { name: 'Flexible Precision Part', description: 'Temporary catalog reference while product photography is incorporated.', categoryName: 'Functional parts', imageAlt: 'Temporary image for TPU product' },
    },
  },
};

export function getHomeContent(language) {
  return content[language === 'en' ? 'en' : 'es'];
}
