export const HERO_PIECES = [
  { id: 'support', image: '/images/hero-soporte.jpg', material: 'PETG PRO', ref: 'REF: PRT-001', tolerance: '±0.05 mm', target: 'M 0 0 L 45 0 L 155 93', dot: [155, 93] },
  { id: 'gear', image: '/images/producto-engranaje.jpg', material: 'NYLON PA12', ref: 'REF: PRT-002', target: 'M 0 0 L 45 0 L 138 76', dot: [138, 76] },
  { id: 'dragon', image: '/images/producto-dragon.jpg', material: 'PLA SILK', ref: 'REF: PRT-003', target: 'M 0 0 L 45 0 L 148 101', dot: [148, 101] },
  { id: 'drone', image: '/images/producto-drone.jpg', material: 'ASA CARBON', ref: 'REF: PRT-004', target: 'M 0 0 L 45 0 L 128 70', dot: [128, 70] },
];

const temporaryProductImage = '/images/producto-temporal.png';

export const FEATURED_PRODUCTS = [
  { id: 'p1', material: 'PETG PRO', stock: 14, stockStatus: 'in-stock', status: 'ACTIVE', images: [temporaryProductImage] },
  { id: 'p2', material: 'NYLON PA12', stock: 21, stockStatus: 'in-stock', status: 'ACTIVE', images: [temporaryProductImage] },
  { id: 'p3', material: 'PLA SILK', stock: 0, stockStatus: 'order', status: 'ACTIVE', images: [temporaryProductImage] },
  { id: 'p4', material: 'ASA CARBON', stock: 8, stockStatus: 'in-stock', status: 'ACTIVE', images: [temporaryProductImage] },
  { id: 'p5', material: 'PLA HIGH DETAIL', stock: 0, stockStatus: 'order', status: 'ACTIVE', images: [temporaryProductImage] },
  { id: 'p6', material: 'RESINA 8K', stock: 1, stockStatus: 'in-stock', status: 'ACTIVE', images: [temporaryProductImage] },
];

const content = {
  es: {
    heroKicker: 'Manufactura aditiva / San José, CR',
    heroTitle: 'Lo que imaginas.',
    heroAccent: 'Hecho preciso.',
    heroLead: 'Piezas funcionales, prototipos y objetos de alto detalle fabricados con criterio técnico, materiales correctos y una revisión humana en cada etapa.',
    explore: 'Explorar piezas',
    hasFile: 'Tengo un archivo',
    capabilities: 'Capacidades principales',
    tolerance: 'Tolerancia objetivo',
    processes: 'Procesos disponibles',
    stagedReview: 'Revisión por etapas',
    stagedValue: 'Por etapas',
    workbench: 'BANCO DE TRABAJO',
    activeReview: 'REVISIÓN ACTIVA',
    previousPiece: 'Pieza anterior',
    nextPiece: 'Pieza siguiente',
    featuredPieces: 'Piezas destacadas',
    catalogKicker: 'Selección de taller',
    catalogTitleA: 'Objetos que',
    catalogTitleB: 'resuelven algo.',
    catalogIntro: 'Una selección de piezas funcionales y modelos de colección. El catálogo muestra referencias; la cotización ocurre después de revisar tu solicitud.',
    methodKicker: 'El método',
    methodTitleA: 'No imprimimos',
    methodTitleB: 'por imprimir.',
    methodTitleC: 'Resolvemos.',
    methodIntro: 'Una pieza empieza mucho antes de tocar la cama de impresión: revisamos geometría, esfuerzo, material y acabado para que el resultado tenga sentido fuera de la pantalla.',
    methods: [
      ['Entender el archivo', 'Revisión de malla, escala, orientación y puntos críticos.'],
      ['Elegir el material', 'Definimos el polímero según esfuerzo, temperatura y acabado.'],
      ['Fabricar con control', 'Impresión aditiva con supervisión y revisión dimensional.'],
      ['Entregar una pieza lista', 'Curado, acabado, verificación y despacho seguro.'],
    ],
    specs: [
      ['A / DIMENSIONAL', '±0.05 mm', 'Tolerancia objetivo para piezas y ajustes que necesitan repetibilidad.', 'VERIFICACIÓN MANUAL'],
      ['B / MATERIALES', 'Polímeros técnicos', 'PETG, Nylon CF, ASA, PLA de detalle y resina para distintos usos.', 'FDM + SLA'],
      ['C / ENTREGAS', 'GAM + 7 provincias', 'Prototipado y entregas coordinadas desde San José, Costa Rica.', 'CORREOS DE COSTA RICA'],
    ],
    projectKicker: 'Tu proyecto',
    projectTitleA: '¿Tenés un archivo',
    projectTitleB: 'que quiere existir?',
    projectIntro: 'Envíanos STL, STEP u OBJ para una revisión técnica antes de cotizar.',
    startRequest: 'Iniciar solicitud',
    viewProduct: 'Ver ficha',
    imageUnavailable: 'Imagen no disponible',
    heroPieces: {
      support: { alt: 'Soporte modular de carga en PETG', process: '/ ESTRUCTURA LATTICE', title: 'Soporte Modular de Carga', description: 'Estructura mecánica con alivios lattice de alta rigidez', tolerance: '±0.05 mm', label: 'Pieza 1, soporte modular' },
      gear: { alt: 'Engranaje helicoidal de precisión en nylon', process: '/ MÓDULO 2.0', title: 'Engranaje Helicoidal 60T', description: 'Transmisión de bajo ruido para ciclos mecánicos continuos', tolerance: 'MÓDULO 2.0', label: 'Pieza 2, engranaje helicoidal' },
      dragon: { alt: 'Dragón geométrico articulado', process: '/ ACABADO IRIDISCENTE', title: 'Dragón de Colección', description: 'Escultura de facetas con articulaciones internas continuas', tolerance: 'ARTICULADO', label: 'Pieza 3, dragón geométrico' },
      drone: { alt: 'Brazo de chasis de drone en ASA', process: '/ RESISTENCIA UV', title: 'Brazo de Chasis Drone', description: 'Estructura tubular para motor brushless y alto impacto', tolerance: 'RESISTENCIA UV', label: 'Pieza 4, brazo de drone' },
    },
    products: {
      p1: { reference: 'REF: PRT-001 · ±0.05 MM', name: 'Soporte de Alta Precisión Modular', description: 'Geometría lattice optimizada con alivios de peso para montajes mecánicos y rigidez estructural.', categoryName: 'Piezas funcionales', stockLabel: 'EN STOCK (14)', imageAlt: 'Imagen temporal para soporte modular PETG' },
      p2: { reference: 'REF: PRT-002 · MÓDULO 2.0', name: 'Engranaje de Nylon de Precisión 60T', description: 'Dientes helicoidales para transmisión de bajo nivel sonoro y resistencia continua al desgaste.', categoryName: 'Mecánica / Robótica', stockLabel: 'EN STOCK (21)', imageAlt: 'Imagen temporal para engranaje de nylon' },
      p3: { reference: 'REF: PRT-003 · IRIDISCENTE', name: 'Dragón de Colección Geométrico', description: 'Escultura low-poly con articulaciones internas continuas, impresa en una sola pieza móvil.', categoryName: 'Colección / Arte', stockLabel: 'BAJO PEDIDO', imageAlt: 'Imagen temporal para pieza de colección' },
      p4: { reference: 'REF: PRT-004 · RESISTENCIA UV', name: 'Brazo de Chasis de Drone Pro', description: 'Estructura tubular con montura para motor brushless y amortiguación elástica de impacto.', categoryName: 'Aeroespacial / Drones', stockLabel: 'EN STOCK (8)', imageAlt: 'Imagen temporal para brazo de chasis de drone' },
      p5: { reference: 'REF: PRT-005 · CAPA 0.08 MM', name: 'Maqueta de Rascacielos Cúbico', description: 'Modelo arquitectónico de precisión con vanos definidos, terrazas y textura de fachada limpia.', categoryName: 'Arquitectura', stockLabel: 'BAJO PEDIDO', imageAlt: 'Imagen temporal para maqueta arquitectónica' },
      p6: { reference: 'REF: PRT-006 · TEMPORAL', name: 'Busto de Precisión Cibernético', description: 'Referencia temporal del catálogo mientras se incorporan fotografías reales de producto.', categoryName: 'Prototipo', stockLabel: 'NUEVO LOTE', imageAlt: 'Imagen temporal para producto de catálogo' },
    },
  },
  en: {
    heroKicker: 'Additive manufacturing / San José, CR',
    heroTitle: 'What you imagine.',
    heroAccent: 'Made precise.',
    heroLead: 'Functional parts, prototypes and high-detail objects made with technical judgment, the right materials and human review at every stage.',
    explore: 'Explore parts',
    hasFile: 'I have a file',
    capabilities: 'Main capabilities',
    tolerance: 'Target tolerance',
    processes: 'Available processes',
    stagedReview: 'Stage-by-stage review',
    stagedValue: 'By stages',
    workbench: 'WORKBENCH',
    activeReview: 'ACTIVE REVIEW',
    previousPiece: 'Previous piece',
    nextPiece: 'Next piece',
    featuredPieces: 'Featured pieces',
    catalogKicker: 'Workshop selection',
    catalogTitleA: 'Objects that',
    catalogTitleB: 'solve something.',
    catalogIntro: 'A selection of functional parts and collectible models. The catalog shows references; quoting happens after your request is reviewed.',
    methodKicker: 'The method',
    methodTitleA: 'We do not print',
    methodTitleB: 'just to print.',
    methodTitleC: 'We solve.',
    methodIntro: 'A part begins long before it reaches the print bed: we review geometry, load, material and finish so the result makes sense beyond the screen.',
    methods: [
      ['Understand the file', 'Review mesh, scale, orientation and critical points.'],
      ['Choose the material', 'We select the polymer according to load, temperature and finish.'],
      ['Manufacture with control', 'Additive manufacturing with supervision and dimensional review.'],
      ['Deliver a ready part', 'Curing, finishing, verification and secure dispatch.'],
    ],
    specs: [
      ['A / DIMENSIONAL', '±0.05 mm', 'Target tolerance for parts and fits that need repeatability.', 'MANUAL VERIFICATION'],
      ['B / MATERIALS', 'Technical polymers', 'PETG, Nylon CF, ASA, detail PLA and resin for different uses.', 'FDM + SLA'],
      ['C / DELIVERY', 'GAM + 7 provinces', 'Prototyping and coordinated deliveries from San José, Costa Rica.', 'CORREOS DE COSTA RICA'],
    ],
    projectKicker: 'Your project',
    projectTitleA: 'Have a file',
    projectTitleB: 'that should exist?',
    projectIntro: 'Send us STL, STEP or OBJ for a technical review before quoting.',
    startRequest: 'Start request',
    viewProduct: 'View details',
    imageUnavailable: 'Image unavailable',
    heroPieces: {
      support: { alt: 'PETG modular load support', process: '/ LATTICE STRUCTURE', title: 'Modular Load Support', description: 'Mechanical structure with high-rigidity lattice reliefs', tolerance: '±0.05 mm', label: 'Piece 1, modular support' },
      gear: { alt: 'Precision nylon helical gear', process: '/ MODULE 2.0', title: '60T Helical Gear', description: 'Low-noise transmission for continuous mechanical cycles', tolerance: 'MODULE 2.0', label: 'Piece 2, helical gear' },
      dragon: { alt: 'Articulated geometric dragon', process: '/ IRIDESCENT FINISH', title: 'Collectible Dragon', description: 'Faceted sculpture with continuous internal joints', tolerance: 'ARTICULATED', label: 'Piece 3, geometric dragon' },
      drone: { alt: 'ASA drone chassis arm', process: '/ UV RESISTANCE', title: 'Drone Chassis Arm', description: 'Tubular structure for brushless motors and high impact', tolerance: 'UV RESISTANCE', label: 'Piece 4, drone arm' },
    },
    products: {
      p1: { reference: 'REF: PRT-001 · ±0.05 MM', name: 'Modular High-Precision Support', description: 'Optimized lattice geometry with weight relief for mechanical assemblies and structural rigidity.', categoryName: 'Functional parts', stockLabel: 'IN STOCK (14)', imageAlt: 'Temporary image for PETG modular support' },
      p2: { reference: 'REF: PRT-002 · MODULE 2.0', name: 'Precision Nylon Gear 60T', description: 'Helical teeth for low-noise transmission and continuous wear resistance.', categoryName: 'Mechanics / Robotics', stockLabel: 'IN STOCK (21)', imageAlt: 'Temporary image for nylon gear' },
      p3: { reference: 'REF: PRT-003 · IRIDESCENT', name: 'Geometric Collectible Dragon', description: 'Low-poly sculpture with continuous internal joints, printed as a single moving piece.', categoryName: 'Collection / Art', stockLabel: 'MADE TO ORDER', imageAlt: 'Temporary image for collectible piece' },
      p4: { reference: 'REF: PRT-004 · UV RESISTANCE', name: 'Pro Drone Chassis Arm', description: 'Tubular structure with brushless motor mount and elastic impact damping.', categoryName: 'Aerospace / Drones', stockLabel: 'IN STOCK (8)', imageAlt: 'Temporary image for drone chassis arm' },
      p5: { reference: 'REF: PRT-005 · 0.08 MM LAYER', name: 'Cubic Tower Architectural Model', description: 'Precision architectural model with defined openings, terraces and a clean facade texture.', categoryName: 'Architecture', stockLabel: 'MADE TO ORDER', imageAlt: 'Temporary image for architectural model' },
      p6: { reference: 'REF: PRT-006 · TEMPORARY', name: 'Cybernetic Precision Bust', description: 'Temporary catalog reference while real product photography is being incorporated.', categoryName: 'Prototype', stockLabel: 'NEW BATCH', imageAlt: 'Temporary image for catalog product' },
    },
  },
};

export function getHomeContent(language) {
  return content[language === 'en' ? 'en' : 'es'];
}
